---
version: "3.3"
services:

  open_appsec_agent:
    image: ghcr.io/openappsec/agent:1.2313-rc2
    container_name: open_appsec_agent
    ipc: host
    volumes:
      - open_appsec_agent_conf:/etc/cp/conf
      - open_appsec_agent_data:/etc/cp/data
    entrypoint: /cp-nano-agent --token ${TOKEN}
    restart: unless-stopped

  docspage:
    image: local/docs-page:dev
    container_name: docspage
    depends_on:
      - open_appsec_agent
    build: ./docs-config
    ports:
      - 7888:80
    restart: unless-stopped

  acmeaudit:
    image: public.ecr.aws/f4q1i2m2/acmeaudit:latest
    container_name: acmeaudit
    depends_on:
      - open_appsec_agent
    ports:
      - 7080:3000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  # juiceshop:
  #   image: bkimminich/juice-shop:v14.5.1
  #   container_name: juiceshop
  #   depends_on:
  #     - open_appsec_agent
  #   ports:
  #     - 7081:3000
  #   volumes:
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   restart: unless-stopped

  reverse_proxy:
    image: ghcr.io/openappsec/nginx-attachment:1.2303.1-rc1-v1.22.1
    container_name: reverse_proxy
    depends_on:
      - docspage
      # - juiceshop
      - acmeaudit
    network_mode: host
    ipc: host
    volumes:
      - ./reverse-proxy-config/nginx:/etc/nginx/conf.d:ro
    privileged: true
    restart: unless-stopped

volumes:
  open_appsec_agent_conf:
  open_appsec_agent_data:
