---
version: "3.3"
services:

  docs_page:
    image: local/docs-page:dev
    container_name: docs_page
    build: docs-config
    ports:
      - 7888:80
    restart: unless-stopped

  webgoat:
    image: webgoat/webgoat:v2023.4
    container_name: webgoat
    ports:
      - 7080:8080
      - 7090:9090
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  reverse_proxy:
    image: ghcr.io/openappsec/nginx-attachment:1.2303.1-rc1-v1.22.1
    container_name: reverse_proxy
    depends_on:
      - docs_page
      - webgoat
    network_mode: host
    ipc: host
    volumes:
      - ./reverse-proxy-config/nginx:/etc/nginx/conf.d:ro
    privileged: true
    restart: unless-stopped

  open_appsec_agent:
    image: ghcr.io/openappsec/agent:1.2313-rc2
    container_name: open_appsec_agent
    ipc: host
    volumes:
      - open_appsec_agent_conf:/etc/cp/conf
      - open_appsec_agent_data:/etc/cp/data
    entrypoint: /cp-nano-agent --token ${TOKEN}
    restart: unless-stopped

volumes:
  open_appsec_agent_conf:
  open_appsec_agent_data:
